### ISSUE TITLE
Increase Database normalization

### ISSUE THREAD

**Issue by wtmenten** [UDubiSchool/tedsrate#12]
tables like userRatingProgress and userRating hold excess data which could be removed through improved normalization.

**Comment by wtmenten** [comment]
redundant data has been purged from the database and the associated php files

**Comment by timca1** [comment]
Great. How'd you do it?

**Comment by wtmenten** [comment]
The userRating table was storing to much information. It now only stores
it's relevant data. It's userRatingProgress ID, the rating value and the
category id. All other columns were describing the userRatingProgress
record.

Also as I was adding the foreign keys I removed all bad data, where the
parent record in another table had been deleted. These records would have
prevented the referential integrity of our system.
