### ISSUE TITLE
Complete Table Renaming

### ISSUE THREAD

**Issue by wtmenten** [UDubiSchool/tedsrate#13]
I am considering renaming the userRatingProgress table to assessment in order to better describe it's function. Then I can also rename userRating to rating to remove the implication that the ratings are associated to user and userProfile to user to be more conventional. 

There are a few more naming convention fixes to be done on some of the tables columns and I would try and add these in at the same time. When all changes are complete I will produce a new ERD to reflect the improved system.

**Comment by timca1** [comment]
That's fine with me

-----Original Message-----

**Comment by wtmenten** [comment]
tables and fields have been renamed to more conventional ones. 
userRating -> rating
userRatingProgress-> assessment
