### ISSUE TITLE
Create new ERD

### ISSUE THREAD

**Issue by wtmenten** [UDubiSchool/tedsrate#16]
create an update ERD diagram to reflect the changes done on the database.

**Comment by wtmenten** [comment]
![tedsrate](https://cloud.githubusercontent.com/assets/10835442/12526823/ac47178a-c126-11e5-96bd-049b9536d74b.png)

**Comment by wtmenten** [comment]
even further improvement all tables referencing langaugeID now have columns name langaugeID. Fixed the personaScenarioID as well.
![tedsrate](https://cloud.githubusercontent.com/assets/10835442/12534028/f8d489a4-c1fb-11e5-94d4-70bb2c7bb04d.png)

**Comment by timca1** [comment]
Cool. Very helpful.
